[package]
name = "spectrum"
version = "1.0.0"
authors = ["Arpan Laha <arpanlaha99@gmail.com>"]
edition = "2018"
description="Create randomly-generated art using Rust + WebAssembly"
repository="https://github.com/arpanlaha/spectrum"
license="MIT"

[lib]
crate-type = ["cdylib"]

# [features]
# default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# console_error_panic_hook = { version = "0.1.1", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
  'CanvasRenderingContext2d',
  'HtmlCanvasElement',
  'ImageData',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlUniformLocation',
  'Document',
  'Element',
  'HtmlElement',
  'HtmlImageElement',
  'HtmlAnchorElement',
  'HtmlInputElement',
  'Node',
  'Window',
  'Storage',
  'Event',
  'CssStyleDeclaration'
]

# [dev-dependencies]
# wasm-bindgen-test = "0.2"

[profile.release]
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']