name: CI

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cargo
            node_modules
            wasm/target/release
          key: ${{ runner.os }}-cache

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Run rustfmt
        working-directory: wasm
        run: cargo fmt -- --check

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Build WebAssembly
        run: wasm-pack build wasm

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install NPM dependencies
        run: npm install

      - name: Run NPM format check
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cargo
            node_modules
            wasm/target/release
          key: ${{ runner.os }}-cache

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Run clippy
        working-directory: wasm
        run: cargo clippy -- -D warnings

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Build WebAssembly
        run: wasm-pack build wasm

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install NPM dependencies
        run: npm install

      - name: Run NPM lint check
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cargo
            node_modules
            wasm/target/release
          key: ${{ runner.os }}-cache

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Build WebAssembly
        run: wasm-pack build wasm

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install NPM dependencies
        run: npm install

      - name: Build and bundle files
        run: npm run build

      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: dist
