name: CI

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cargo
            node_modules
          key: ${{ runner.os }}-cache

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Build WebAssembly
        run: |
          wasm-pack build wasm

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Build and bundle files
        run: |
          npm run build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        run: /
          az storage blob upload-batch -s dist -d \$web --account-name $AZURE_STORAGE_ACCOUNT
